export const Movies = [
    {
        id: 1,
        title: "Leo",
        image: "https://upload.wikimedia.org/wikipedia/en/7/75/Leo_%282023_Indian_film%29.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 2,
        title: "Kannur Squad",
        image: "https://upload.wikimedia.org/wikipedia/en/7/75/Kannur_Squad_poster.jpeg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 3,
        title: "Jigarthanda DoubleX",
        image: "https://upload.wikimedia.org/wikipedia/en/4/4e/Jigarthanda_DoubleX.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 4,
        title: "Mark Antony",
        image: "https://upload.wikimedia.org/wikipedia/en/4/40/Mark_Antony_2023_poster.jpg",
        price: 150,
        language: "Tamil",
    },
    {
        id: 5,
        title: "Irugapatru",
        image: "https://upload.wikimedia.org/wikipedia/en/0/09/Irugapatru.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 6,
        title: "Jailer",
        image: "https://upload.wikimedia.org/wikipedia/en/c/cb/Jailer_2023_Tamil_film_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 7,
        title: "Ghost",
        image: "https://upload.wikimedia.org/wikipedia/en/c/c2/Ghost_Kannada_Film.jpg",
        price: 150,
        language: "Kannada",
    },
    {
        id: 8,
        title: "RDX: Robert Dony Xavier",
        image: "https://upload.wikimedia.org/wikipedia/en/b/be/RDX-_Robert_Dony_Xavier_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 9,
        title: "Kaithi",
        image: "https://upload.wikimedia.org/wikipedia/en/7/79/Kaithi_2019_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 10,
        title: "The Matrix",
        image: "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 11,
        title: "Dune",
        image: "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 12,
        title: "Spider-Man: No Way Home",
        image: "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 13,
        title: "The Dark Knight",
        image: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 14,
        title: "Beast",
        image: "https://upload.wikimedia.org/wikipedia/en/3/3d/Beast_2022_Indian_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 15,
        title: "Asuran",
        image: "https://upload.wikimedia.org/wikipedia/en/7/78/Asuran_2019_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 16,
        title: "Avengers",
        image: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 17,
        title: "John Wick",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d0/John_Wick_-_Chapter_4_promotional_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 18,
        title: "Thunivu",
        image: "https://upload.wikimedia.org/wikipedia/en/6/65/Thunivu_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 19,
        title: "The Marvels",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7a/The_Marvels_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 20,
        title: "Vikram",
        image: "https://upload.wikimedia.org/wikipedia/en/9/93/Vikram_2022_poster.jpg",
        price: 120,
        language: "Tamil",
    },
    {
        id: 21,
        title: "Khufiya",
        image: "https://upload.wikimedia.org/wikipedia/en/b/bf/Khufiya_poster.jpg",
        price: 160,
        language: "Hindi",
    },
    {
        id: 22,
        title: "OMG",
        image: "https://upload.wikimedia.org/wikipedia/en/5/56/OMG_2_%E2%80%93_Oh_My_God%21_2_poster.jpg",
        price: 180,
        language: "Hindi",
    },
    {
        id: 23,
        title: "Trance",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d5/Trance_film_poster.jpg",
        price: 150,
        language: "Telugu",
    },
    {
        id: 24,
        title: "RRR",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d7/RRR_Poster.jpg",
        price: 150,
        language: "Telugu",
    },
]

const Screens = [
    {
        id: 1,
        time: "9.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 2,
        time: "10.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 3,
        time: "11.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 4,
        time: "12.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 5,
        time: "1.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 6,
        time: "2.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 7,
        time: "3.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 8,
        time: "4.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    {
        id: 9,
        time: "5.30 AM",
        seats: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
]

export default Screens;
