export const Movies = [
    {
        id: 1,
        title: "Leo",
        image: "https://upload.wikimedia.org/wikipedia/en/7/75/Leo_%282023_Indian_film%29.jpg",
        price: 180,
        language: "Tamil",
        theatres: [
            {
                id: "A-1",
                name: "INOX : LUXE",
            }
        ]
    },
    {
        id: 2,
        title: "Kannur Squad",
        image: "https://upload.wikimedia.org/wikipedia/en/7/75/Kannur_Squad_poster.jpeg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 3,
        title: "Jigarthanda DoubleX",
        image: "https://upload.wikimedia.org/wikipedia/en/4/4e/Jigarthanda_DoubleX.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 4,
        title: "Mark Antony",
        image: "https://upload.wikimedia.org/wikipedia/en/4/40/Mark_Antony_2023_poster.jpg",
        price: 150,
        language: "Tamil",
    },
    {
        id: 5,
        title: "Irugapatru",
        image: "https://upload.wikimedia.org/wikipedia/en/0/09/Irugapatru.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 6,
        title: "Jailer",
        image: "https://upload.wikimedia.org/wikipedia/en/c/cb/Jailer_2023_Tamil_film_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 7,
        title: "Ghost",
        image: "https://upload.wikimedia.org/wikipedia/en/c/c2/Ghost_Kannada_Film.jpg",
        price: 150,
        language: "Kannada",
    },
    {
        id: 8,
        title: "RDX: Robert Dony Xavier",
        image: "https://upload.wikimedia.org/wikipedia/en/b/be/RDX-_Robert_Dony_Xavier_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 9,
        title: "Kaithi",
        image: "https://upload.wikimedia.org/wikipedia/en/7/79/Kaithi_2019_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 10,
        title: "The Matrix",
        image: "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 11,
        title: "Dune",
        image: "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 12,
        title: "Spider-Man: No Way Home",
        image: "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 13,
        title: "The Dark Knight",
        image: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 14,
        title: "Beast",
        image: "https://upload.wikimedia.org/wikipedia/en/3/3d/Beast_2022_Indian_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 15,
        title: "Asuran",
        image: "https://upload.wikimedia.org/wikipedia/en/7/78/Asuran_2019_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 16,
        title: "Avengers",
        image: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 17,
        title: "John Wick",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d0/John_Wick_-_Chapter_4_promotional_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 18,
        title: "Thunivu",
        image: "https://upload.wikimedia.org/wikipedia/en/6/65/Thunivu_poster.jpg",
        price: 180,
        language: "Tamil",
    },
    {
        id: 19,
        title: "The Marvels",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7a/The_Marvels_poster.jpg",
        price: 200,
        language: "English",
    },
    {
        id: 20,
        title: "Vikram",
        image: "https://upload.wikimedia.org/wikipedia/en/9/93/Vikram_2022_poster.jpg",
        price: 120,
        language: "Tamil",
    },
    {
        id: 21,
        title: "Khufiya",
        image: "https://upload.wikimedia.org/wikipedia/en/b/bf/Khufiya_poster.jpg",
        price: 160,
        language: "Hindi",
    },
    {
        id: 22,
        title: "OMG",
        image: "https://upload.wikimedia.org/wikipedia/en/5/56/OMG_2_%E2%80%93_Oh_My_God%21_2_poster.jpg",
        price: 180,
        language: "Hindi",
    },
    {
        id: 23,
        title: "Trance",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d5/Trance_film_poster.jpg",
        price: 150,
        language: "Telugu",
    },
    {
        id: 24,
        title: "RRR",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d7/RRR_Poster.jpg",
        price: 150,
        language: "Telugu",
    },
]

const Screens = [
    {
        id: 1,
        time: "9.30 AM",
        seats: [
            {
                id: "S-01",
                name: "A1",
                booked: true,
            },
            {
                id: "S-02",
                name: "A2",
                booked: false,
            },
            {
                id: "S-03",
                name: "A3",
                booked: true,
            },
            {
                id: "S-04",
                name: "A4",
                booked: false,
            },
            {
                id: "S-05",
                name: "A5",
                booked: false,
            },
            {
                id: "S-06",
                name: "A6",
                booked: false,
            },
            {
                id: "S-07",
                name: "A7",
                booked: true,
            },
            {
                id: "S-08",
                name: "A8",
                booked: false,
            },
            {
                id: "S-09",
                name: "A9",
                booked: true,
            },
            {
                id: "S-10",
                name: "A10",
                booked: true,
            },
            {
                id: "S-11",
                name: "A11",
                booked: false,
            },
            {
                id: "S-12",
                name: "A12",
                booked: true,
            },
            {
                id: "S-13",
                name: "A13",
                booked: true,
            },
            {
                id: "S-14",
                name: "A14",
                booked: false,
            },
            {
                id: "S-15",
                name: "A15",
                booked: true,
            },
            {
                id: "S-16",
                name: "A16",
                booked: false,
            },
            {
                id: "S-17",
                name: "A17",
                booked: false,
            },
            {
                id: "S-18",
                name: "A18",
                booked: false,
            },
            {
                id: "S-19",
                name: "A19",
                booked: true,
            },
            {
                id: "S-20",
                name: "A20",
                booked: false,
            },
            {
                id: "S-21",
                name: "A21",
                booked: true,
            },
            {
                id: "S-22",
                name: "A22",
                booked: true,
            },
        ],
    },
    {
        id: 2,
        time: "10.30 AM",
        seats: [
            {
                id: "T-01",
                name: "B1",
                booked: false,
            },
            {
                id: "T-02",
                name: "B2",
                booked: true,
            },
            {
                id: "T-03",
                name: "B3",
                booked: false,
            },
            {
                id: "T-04",
                name: "B4",
                booked: true,
            },
            {
                id: "T-05",
                name: "B5",
                booked: false,
            },
            {
                id: "T-06",
                name: "B6",
                booked: false,
            },
            {
                id: "T-07",
                name: "B7",
                booked: false,
            },
            {
                id: "T-08",
                name: "B8",
                booked: true,
            },
            {
                id: "T-09",
                name: "B9",
                booked: false,
            },
            {
                id: "T-10",
                name: "B10",
                booked: true,
            },
            {
                id: "T-11",
                name: "B11",
                booked: false,
            },
            {
                id: "T-12",
                name: "B12",
                booked: false,
            },
            {
                id: "T-13",
                name: "B13",
                booked: false,
            },
            {
                id: "T-14",
                name: "B14",
                booked: true,
            },
            {
                id: "T-15",
                name: "B15",
                booked: false,
            },
            {
                id: "T-16",
                name: "B16",
                booked: true,
            },
            {
                id: "T-17",
                name: "B17",
                booked: false,
            },
            {
                id: "T-18",
                name: "B18",
                booked: false,
            },
            {
                id: "T-19",
                name: "B19",
                booked: false,
            },
            {
                id: "T-20",
                name: "B20",
                booked: true,
            },
            {
                id: "T-21",
                name: "B21",
                booked: false,
            },
            {
                id: "T-22",
                name: "B22",
                booked: true,
            },
            {
                id: "T-23",
                name: "B23",
                booked: false,
            },
            {
                id: "T-24",
                name: "B24",
                booked: false,
            },
        ],
    },
    {
        id: 3,
        time: "11.30 AM",
        seats: [
            {
                id: "U-01",
                name: "C1",
                booked: false,
            },
            {
                id: "U-02",
                name: "C2",
                booked: true,
            },
            {
                id: "U-03",
                name: "C3",
                booked: false,
            },
            {
                id: "U-04",
                name: "C4",
                booked: false,
            },
            {
                id: "U-05",
                name: "C5",
                booked: false,
            },
            {
                id: "U-06",
                name: "C6",
                booked: true,
            },
            {
                id: "U-07",
                name: "C7",
                booked: false,
            },
            {
                id: "U-08",
                name: "C8",
                booked: true,
            },
            {
                id: "U-09",
                name: "C9",
                booked: false,
            },
            {
                id: "U-10",
                name: "C10",
                booked: false,
            },
            {
                id: "U-11",
                name: "C11",
                booked: false,
            },
            {
                id: "U-12",
                name: "C12",
                booked: true,
            },
            {
                id: "U-13",
                name: "C13",
                booked: false,
            },
            {
                id: "U-14",
                name: "C14",
                booked: true,
            },
            {
                id: "U-15",
                name: "C15",
                booked: false,
            },
            {
                id: "U-16",
                name: "C16",
                booked: false,
            },
            {
                id: "U-17",
                name: "C17",
                booked: false,
            },
            {
                id: "U-18",
                name: "C18",
                booked: true,
            },
            {
                id: "U-19",
                name: "C19",
                booked: false,
            },
            {
                id: "U-20",
                name: "C20",
                booked: true,
            },
            {
                id: "U-21",
                name: "C21",
                booked: false,
            },
            {
                id: "U-22",
                name: "C22",
                booked: false,
            },
            {
                id: "U-23",
                name: "C23",
                booked: false,
            },
            {
                id: "U-24",
                name: "C24",
                booked: true,
            },
        ],
    },
    {
        id: 4,
        time: "12.30 AM",
        seats: [
            {
                id: "V-01",
                name: "D1",
                booked: false,
                price: 200,
            },
            {
                id: "V-02",
                name: "D2",
                booked: false,
                price: 200,
            },
            {
                id: "V-03",
                name: "D3",
                booked: true,
                price: 200,
            },
            {
                id: "V-04",
                name: "D4",
                booked: true,
                price: 200,
            },
            {
                id: "V-05",
                name: "D5",
                booked: false,
                price: 200,
            },
            {
                id: "V-06",
                name: "D6",
                booked: false,
                price: 200,
            },
            {
                id: "V-07",
                name: "D7",
                booked: false,
                price: 200,
            },
            {
                id: "V-08",
                name: "D8",
                booked: false,
                price: 200,
            },
            {
                id: "V-09",
                name: "D9",
                booked: true,
                price: 200,
            },
            {
                id: "V-10",
                name: "D10",
                booked: true,
                price: 200,
            },
            {
                id: "V-11",
                name: "D11",
                booked: false,
                price: 200,
            },
            {
                id: "V-12",
                name: "D12",
                booked: false,
                price: 200,
            },
            {
                id: "V-13",
                name: "D13",
                booked: false,
                price: 160,
            },
            {
                id: "V-14",
                name: "D14",
                booked: false,
                price: 160,
            },
            {
                id: "V-15",
                name: "D15",
                booked: true,
                price: 160,
            },
            {
                id: "V-16",
                name: "D16",
                booked: true,
                price: 160,
            },
            {
                id: "V-17",
                name: "D17",
                booked: false,
                price: 160,
            },
            {
                id: "V-18",
                name: "D18",
                booked: false,
                price: 160,
            },
            {
                id: "V-19",
                name: "D19",
                booked: false,
                price: 160,
            },
            {
                id: "V-20",
                name: "D20",
                booked: false,
                price: 160,
            },
            {
                id: "V-21",
                name: "D21",
                booked: true,
                price: 160,
            },
            {
                id: "V-22",
                name: "D22",
                booked: true,
                price: 160,
            },
            {
                id: "V-23",
                name: "D23",
                booked: false,
                price: 160,
            },
            {
                id: "V-24",
                name: "D24",
                booked: false,
                price: 160,
            },
        ],
    },
]

export default Screens;
